"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import clsx from "clsx";
import { Activity, Check, Clock3, Cpu, Layers3, Play, Plus, ServerCog } from "lucide-react";
import { getStudentDashboard, saveScenario, startLab, type ApiLab, type ApiMachine, type ApiScenario, type StudentDashboard } from "@/lib/api";

function Panel({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) {
  return <section className="rounded-lg border border-ink/10 bg-white shadow-sm"><div className="border-b border-ink/10 p-4"><p className="text-xs font-bold uppercase text-ink/44">{eyebrow}</p><h2 className="mt-1 text-xl font-black text-ink">{title}</h2></div>{children}</section>;
}

function Action({ children, icon: Icon, onClick, disabled }: { children: React.ReactNode; icon: typeof Play; onClick?: () => void; disabled?: boolean }) {
  return <button type="button" onClick={onClick} disabled={disabled} className={clsx("inline-flex min-h-10 items-center justify-center gap-2 rounded-md px-3 text-sm font-bold", disabled ? "cursor-not-allowed bg-ink/8 text-ink/35" : "bg-canopy text-white hover:bg-fern")}><Icon size={16} />{children}</button>;
}

function LabRows({ labs, machines, launching, onLaunch }: { labs: ApiLab[]; machines: ApiMachine[]; launching: string | null; onLaunch: (lab: ApiLab) => void }) {
  return <div className="divide-y divide-ink/10">{labs.map((lab) => {
    const locked = lab.status === "locked";
    const running = lab.status === "running";
    const machineNames = lab.machine_ids.map((id) => machines.find((machine) => machine.id === id)?.name).filter(Boolean).join(", ");
    return <article key={lab.id} className="p-4"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-base font-black text-ink">{lab.name}</h3><span className={clsx("rounded-full px-2.5 py-1 text-xs font-bold", locked ? "bg-ink/8 text-ink/45" : running ? "bg-mint/25 text-fern" : "bg-sun/20 text-ink/70")}>{locked ? "Locked" : running ? "Running" : "Ready"}</span></div><p className="mt-1 text-sm leading-6 text-ink/58">{lab.description}</p><p className="mt-2 text-xs font-semibold text-ink/48">{lab.level} - {lab.runtime} - {machineNames}</p></div><Action icon={running ? Activity : Play} onClick={() => onLaunch(lab)} disabled={locked || launching === lab.id}>{locked ? "Locked" : launching === lab.id ? "Preparing" : running ? "Resume" : "Launch"}</Action></div><div className="mt-4 flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-cloud"><div className="h-full rounded-full bg-fern" style={{ width: lab.progress + "%" }} /></div><span className="text-xs font-bold text-ink/55">{lab.progress}%</span></div><p className="mt-2 text-xs text-ink/52"><span className="font-bold text-fern">Next:</span> {lab.next_step}</p></article>;
  })}</div>;
}

function Builder({ apiUrl, machines, scenarios, onSaved }: { apiUrl: string; machines: ApiMachine[]; scenarios: ApiScenario[]; onSaved: (scenario: ApiScenario) => void }) {
  const [name, setName] = useState(""); const [selected, setSelected] = useState(["machine-kali", "machine-dvwa"]); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  function toggle(id: string) { setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!name.trim() || !selected.length) { setError(!name.trim() ? "Enter a scenario name." : "Select at least one approved machine."); return; } setSaving(true); setError(""); try { onSaved(await saveScenario(apiUrl, name, selected)); setName(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save the scenario."); } finally { setSaving(false); } }
  return <div className="grid gap-6 xl:grid-cols-[minmax(0,1.1fr)_minmax(320px,0.9fr)]"><Panel eyebrow="Scenario builder" title="Create a personal lab"><form onSubmit={submit} className="p-4"><label className="block text-sm font-bold text-ink/72">Scenario name<input value={name} onChange={(event) => setName(event.target.value)} className="mt-2 block min-h-11 w-full rounded-md border border-ink/15 px-3 outline-none focus:border-fern" placeholder="e.g. Web request investigation" /></label><p className="mt-5 text-sm font-black text-ink">Approved machine layout</p><p className="mt-1 text-xs leading-5 text-ink/54">Personal scenarios can only use machines approved by a teacher or administrator.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{machines.map((machine) => { const checked = selected.includes(machine.id); return <button key={machine.id} type="button" onClick={() => toggle(machine.id)} className={clsx("rounded-md border p-3 text-left transition", checked ? "border-fern bg-mint/10" : "border-ink/10 hover:border-fern/50")}><span className="flex items-center justify-between"><Cpu size={18} className="text-canopy" /><span className={clsx("grid h-5 w-5 place-items-center rounded-full", checked ? "bg-fern text-white" : "bg-ink/10 text-transparent")}><Check size={13} /></span></span><p className="mt-3 text-sm font-black text-ink">{machine.name}</p><p className="mt-1 text-xs text-ink/50">{machine.os_type}</p></button>; })}</div>{error ? <p className="mt-4 rounded-md bg-clay/10 px-3 py-2 text-sm font-semibold text-clay">{error}</p> : null}<div className="mt-5 flex justify-end"><Action icon={Plus} disabled={saving}>{saving ? "Saving" : "Save scenario"}</Action></div></form></Panel><Panel eyebrow="Saved scenarios" title="Your workspace library"><div className="divide-y divide-ink/10">{scenarios.map((scenario) => <div key={scenario.id} className="p-4"><div className="flex justify-between gap-3"><div><p className="text-sm font-black text-ink">{scenario.name}</p><p className="mt-1 text-xs text-ink/54">{scenario.machine_ids.length} approved machines</p></div><span className="rounded-full bg-mint/20 px-2.5 py-1 text-xs font-bold text-fern">Saved</span></div><p className="mt-3 text-xs font-semibold text-ink/45">Updated {scenario.updated_at}</p></div>)}</div></Panel></div>;
}

export default function StudentPortal({ apiUrl, view }: { apiUrl: string; view: string }) {
  const [data, setData] = useState<StudentDashboard | null>(null); const [error, setError] = useState(""); const [launching, setLaunching] = useState<string | null>(null); const [notice, setNotice] = useState(""); const [scenarios, setScenarios] = useState<ApiScenario[]>([]);
  useEffect(() => { let active = true; getStudentDashboard(apiUrl).then((dashboard) => { if (active) { setData(dashboard); setScenarios(dashboard.scenarios); } }).catch((reason) => active && setError(reason instanceof Error ? reason.message : "Unable to load your workspace.")); return () => { active = false; }; }, [apiUrl]);
  const progress = useMemo(() => data ? Math.round(data.assignments.reduce((sum, lab) => sum + lab.progress, 0) / data.assignments.length) : 0, [data]);
  async function launch(lab: ApiLab) { setLaunching(lab.id); setNotice(""); try { const result = await startLab(apiUrl, lab.id); setNotice(result.message + " Access address: " + result.access_url); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Unable to prepare the lab."); } finally { setLaunching(null); } }
  if (error) return <p className="rounded-lg border border-clay/25 bg-clay/10 p-4 text-sm font-semibold text-clay">{error}</p>;
  if (!data) return <p className="rounded-lg border border-ink/10 bg-white p-8 text-center text-sm font-semibold text-ink/58">Loading your learning workspace...</p>;
  const labs = <Panel eyebrow="Assigned labs" title="Continue learning"><LabRows labs={data.assignments} machines={data.machines} launching={launching} onLaunch={launch} /></Panel>;
  const builder = <Builder apiUrl={apiUrl} machines={data.machines} scenarios={scenarios} onSaved={(scenario) => { setScenarios((items) => [scenario, ...items]); setNotice(scenario.name + " has been saved to your workspace."); }} />;
  const library = <Panel eyebrow="Machine library" title="Approved environments"><div className="grid divide-y divide-ink/10 sm:grid-cols-2 sm:divide-x sm:divide-y-0">{data.machines.map((machine) => <div key={machine.id} className="p-4"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-md bg-mint/20 text-canopy"><ServerCog size={19} /></span><span className="rounded-md bg-cloud px-2 py-1 text-xs font-bold text-ink/55">{machine.os_type}</span></div><p className="mt-4 text-sm font-black text-ink">{machine.name}</p><p className="mt-1 text-xs leading-5 text-ink/54">{machine.description}</p><p className="mt-3 truncate text-xs font-semibold text-fern">{machine.imageUrl}</p></div>)}</div></Panel>;
  if (view === "Assigned labs") return <div className="space-y-4">{notice ? <p className="rounded-lg border border-fern/25 bg-mint/15 px-4 py-3 text-sm font-bold text-fern">{notice}</p> : null}{labs}</div>;
  if (view === "My scenarios") return <div className="space-y-4">{notice ? <p className="rounded-lg border border-fern/25 bg-mint/15 px-4 py-3 text-sm font-bold text-fern">{notice}</p> : null}{builder}</div>;
  if (view === "Machine library") return library;
  return <div className="space-y-6">{notice ? <p className="rounded-lg border border-fern/25 bg-mint/15 px-4 py-3 text-sm font-bold text-fern">{notice}</p> : null}<div className="grid gap-4 md:grid-cols-3">{[["Active labs", String(data.assignments.filter((lab) => lab.status === "running").length), "ready to resume", Play], ["Learning progress", progress + "%", "across assigned labs", Activity], ["Personal scenarios", String(scenarios.length), "saved workspaces", Layers3]].map(([label, value, detail, Icon]) => { const Metric = Icon as typeof Activity; return <div key={label as string} className="rounded-lg border border-ink/10 bg-white p-4 shadow-sm"><div className="flex justify-between"><div><p className="text-sm font-semibold text-ink/55">{label as string}</p><p className="mt-2 text-3xl font-black text-ink">{value as string}</p></div><span className="grid h-10 w-10 place-items-center rounded-md bg-mint/20 text-canopy"><Metric size={20} /></span></div><p className="mt-3 text-xs font-bold text-fern">{detail as string}</p></div>; })}</div><div className="grid gap-6 xl:grid-cols-[minmax(0,1.15fr)_minmax(320px,0.85fr)]">{labs}<Panel eyebrow="Recent activity" title="Your progress"><div className="divide-y divide-ink/10">{data.activity.map((item) => <div key={item.id} className="flex gap-3 p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-cloud text-fern"><Clock3 size={16} /></span><div><p className="text-sm font-black text-ink">{item.title}</p><p className="mt-1 text-xs text-ink/54">{item.detail}</p><p className="mt-2 text-xs font-semibold text-ink/42">{item.when}</p></div></div>)}</div></Panel></div>{builder}</div>;
}
