[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name          forward
    Listen        0.0.0.0
    Port          24224
    Tag           mayajal.forward

[FILTER]
    Name          modify
    Match         mayajal.*
    Add           platform mayajal

[OUTPUT]
    Name                  opensearch
    Match                 mayajal.*
    Host                  opensearch
    Port                  9200
    Index                 mayajal-logs
    Logstash_Format       On
    Logstash_Prefix       mayajal-logs
    Replace_Dots          On
    Suppress_Type_Name    On
    Retry_Limit           False
