name: Deploy to test
run-name: ${{ github.actor }} is deploying to test.
on: 
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Deploy Via SSH
        uses: appleboy/ssh-action@1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/mayajal
            git pull
            cd ./api
            uv run fastapi dev main.py --host 0.0.0.0
